### ISSUE TITLE
Need help in improving docs!

### ISSUE THREAD

**Issue by Gregivy** [Gregivy/simpleddp#1]

**Comment by Gregivy** [comment]
1. Include calling methods in **Usage**
2. Write Ionic part
3. Improve code style
4. Improve description itself
5. Correct mistakes in English

**Comment by navi8602** [comment]
@Gregivy To read the documentation for a connection with ionic or an example

**Comment by Gregivy** [comment]
@navi8602 Hello! You can check the updated docs with ionic example.

**Comment by navi8602** [comment]
@Gregivy it's great ))) Thanks for the update

**Comment by Gregivy** [comment]
@navi8602 There was an error in ionic example, you should use 'on' instead of 'addEvent'.

**Comment by Gregivy** [comment]
@navi8602 Btw I'm hiring people for some meteor project if you are interested write me gpoi@mail.ru

**Comment by navi8602** [comment]
@Gregivy Yes, I did so! Now I will try to authorize the user

**Comment by navi8602** [comment]
@Gregivy Well, I'll write you

**Comment by navi8602** [comment]
@Gregivy Do you speak Russian ?

**Comment by Gregivy** [comment]
@navi8602 Yes

**Comment by navi8602** [comment]
@Gregivy Nice! Я был бы рад помочь в развитии )

**Comment by Gregivy** [comment]
@navi8602 Отлично! Планов много, есть чем заняться. Конкретно по DDP, правильно заметил, надо удобно реализовать авторизацию. Потом перевод документации на русский, больше примеров на разные среды, исправление ошибок ну и, конечно, улучшение того, что есть)

**Comment by navi8602** [comment]
@Gregivy Да, авторизация тут основа основ! Как по email так и по телефону. Я сейчас уже получил вариант авторизации по email теперь хочу реализовать по средствам мобильного телефона. Отпишусь на почту о результатах )

**Comment by Gregivy** [comment]
@navi8602 Если есть какой-нибудь пакет для метеора с телефоном, то достаточно просто вызвать метод login с телефоном соотвественно. Или, как вариант, можно на сервере свой метод сделать, который будет сперва определять, например, почту по номеру телефона, а потом проводить стандартную авторизацию:
`
function loginWithPhone(phone,password) {
let usermail = Meteor.users.findOne({phone}).user.email[0];
return Meteor.call("login",{password,user:{email:usermail}});
}
`

**Comment by Gregivy** [comment]
@navi8602 Пиши, тоже интересно, что получится)
