### ISSUE TITLE
subscribe to same publication twice, the seconds one will not work.

### ISSUE THREAD

**Issue by imhazige** [Gregivy/simpleddp#11]
I have tried sub and subscribe, the first time, it will work.

then the seconds time, will never trigger the ready state.

I have used the login plugin.

**Comment by imhazige** [comment]
first time, it work.
![image](https://user-images.githubusercontent.com/4122902/62769798-4c6fc980-bacc-11e9-8401-8121df905923.png)

then logout, login again, sub the seconds time with the same server object.

**Comment by imhazige** [comment]
I noticed the _nosub, what's that mean?

**Comment by imhazige** [comment]
@Gregivy please help

**Comment by Gregivy** [comment]
Hello @imhazige! I was not able to reproduce this error, can you show me the example code, please?

**Comment by imhazige** [comment]
ok, can you send me your gitlab account, I will add you to the project.
my gtalk is imhazige, hope I can connect to you.

**Comment by Gregivy** [comment]
'_nosub' means that server responded with error or unsubscribed you if its value is true

**Comment by imhazige** [comment]
the code is connecting to the dev server, which is working for a long time, so I think the server have no problem.

**Comment by imhazige** [comment]
I have add you to the project, @Gregivy

**Comment by imhazige** [comment]
https://github.com/imhazige/meteor-ddp-client-test/invitations

I have add the README.md

**Comment by Gregivy** [comment]
So you manually login, then logout, then login again and subscription does not work. From your logs I see that `subscriptionId `is the same in both cases which means that you have not tried to restart the subscription. When you logout the server sends `nosub` message, so *simpleddp* stops the subscription but the `ddpSubscription` object is not destroyed. Next time you login you try to subscribe with the same parameters, *simpleddp* sees that and does nothing but return you your previous subscription (which is stopped). I think I can improve this behavior and in next *simpleddp* releases your code will work. For now you should remove your subscription when your home page dies.

**Comment by imhazige** [comment]
@Gregivy Thanks, I will have a try now, I have tried remove yesterday, still not work. I will try restart.

**Comment by Gregivy** [comment]
Instead of `let userSub = server.subscribe("account.info");` put subscription in some page variables, then use `destroyed` hook in your *home.vue* component and do something like this
```
this.userSub.remove();
this.userSub = null;
```

**Comment by imhazige** [comment]
ok

**Comment by imhazige** [comment]
It works! thank you so much! @Gregivy

**Comment by Gregivy** [comment]
You are welcome :)
