### ISSUE TITLE
Why isomorphic-ws?

### ISSUE THREAD

**Issue by leprekon91** [Gregivy/simpleddp#14]
Why not use the regular `ws` package instead? 
I can't seem to find out what the isomorphic package does differently anywhere, and you use the regular `ws` in all of the tests. Does it matter what I use? And if not can I use other socket interfaces like [uWebSocket](https://github.com/uNetworking/uWebSockets.js)?

**Comment by Gregivy** [comment]
Isomorphic package does nothing more than in case of a browser it uses native `WebSocket` and in case of node.js it uses `ws` package. It does not matter what you use the only restriction is that your web socket implementation should correspond with https://developer.mozilla.org/en-US/docs/Web/API/WebSocket.

`uWebSockets.js` is a server not a client. `SimpleDDP` is a client for `Meteor.js` server, it is possible to use `Meteor.js` with `uWebSockets.js` but not straightforward, anyway this doesn't affect `SimpleDDP`.

**Comment by leprekon91** [comment]
Thanks!
