### ISSUE TITLE
Use simple-DDP in the browser

### ISSUE THREAD

**Issue by Floriferous** [Gregivy/simpleddp#19]
I'm planning to use this library in the browser, through a Gatsby website. 

Do you still need a SocketConstructor, like `isomorphic-ws`? And if so, any light-weight library that would be optimal for that use case?

**Comment by Gregivy** [comment]
Hi. You use `isomorphic-ws` only when your code runs both on server and on client. In case of a browser only you can simply use `WebSocket` object, it is built in browsers https://developer.mozilla.org/ru/docs/WebSockets
