### ISSUE TITLE
Handling "connection error"

### ISSUE THREAD

**Issue by hems** [Gregivy/simpleddp#21]
Currently when the webserver is down for maintenance i get the following error on my Browser console.

````socket.js:64 WebSocket connection to 'ws://[...]/websocket' failed: Error during WebSocket handshake: Unexpected response code: 503````

Is that a way of gracefully handling connection errors so they don't end up in the Browser Console and the application can deal with them programmatically, for instance showing an UI element.

**Comment by Gregivy** [comment]
Try to use `try {await server.connect()} catch(error) {/*error logic here*/}`

**Comment by hems** [comment]
Still hangs forever and never throws.. You can reproduce this way:

````js
const opts = {
  endpoint: 'wss://google.com',
  SocketConstructor: ws,
  reconnectInterval: 500,
};

;(async () =>{
  try {
    console.log("will hang")
    await DDP.connect()
    console.log("this never gets logged!")
  } catch(error) {
    console.log("this never happens too", error)
  }

  console.log("executed 2")
})()
````

**Comment by hems** [comment]
If i set a "maxTimeout" then i get a Error as you can see on the [your source code here](maxTimeout: 1000) but that error has no message, but i can see the `socket.js` stays retrying anyway, maybe "socket.close" should also be called when the max timeout is reached?

Does the same happen to you?

![image](https://user-images.githubusercontent.com/27327/79015224-4868df80-7b64-11ea-9019-e8de463be00b.png)

**Comment by Gregivy** [comment]
Try
```js
const opts = {
  endpoint: 'wss://google.com',
  SocketConstructor: ws,
  reconnectInterval: 500,
  autoConnect: false
};
```

**Comment by Gregivy** [comment]
Concerning the `maxTimeout` it is only for method calls.

**Comment by Gregivy** [comment]
Also don't forget that you have these events:

```js
server.on('connected', () => {
    // do something
});

server.on('disconnected', () => {
    // for example show alert to user
});

server.on('error', (e) => {
    // global errors from server
});
```
