### ISSUE TITLE
How to set header?

### ISSUE THREAD

**Issue by ddaydd** [Gregivy/simpleddp#27]
Hi,

how to set headers to a simpleddp client like

`let opts = {
  endpoint: "ws://hard.homedoudou.fr/websocket",
  SocketConstructor: ws,
  reconnectInterval: 5000,
  headers: { 'User-Agent': 'nabaztag/0.1' }
};`

Thanks

**Comment by Gregivy** [comment]
Hello!

Unfortunately *there is no method in the JavaScript WebSockets API for specifying additional headers for the client/browser to send*. https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api.

You can use methods to send additional information like `User-Agent`.

**Comment by ddaydd** [comment]
maybe not in pure websocket but maybe in ddp?

`DDP.connect('http://localhost:3000',{
  headers: {
    "User-Agent": 'my-white-listed-string'
  }
})`

https://forums.meteor.com/t/adding-connection-headers-on-ddp/38989/2

**Comment by Gregivy** [comment]
`SimpleDDP` use any `WebSockets API` compatible constructor but it doesn't support anything out of the spec. I have not tried it myself but you should be able to use `SockJS` client (https://www.npmjs.com/package/sockjs-client) instead of the `WebSocket`.

Something like this:
```js
const simpleDDP = require("simpleddp"); // nodejs
const SockJS = require("sockjs-client");

let opts = {
    endpoint: "ws://someserver.com/websocket",
    SocketConstructor: (endpoint) => SockJS(endpoint, {headers: {"User-Agent": "my-white-listed-string"}}),
    reconnectInterval: 5000
};
const server = new simpleDDP(opts);
```

**Comment by ddaydd** [comment]
Hi @Gregivy 

Thanks to your help i finally succeeded with "ws"

```javascript

const simpleDDP = require("simpleddp");
const ws = require("ws");

const optsDDP = {
  endpoint: "ws://hard.homedoudou.fr/websocket",
  SocketConstructor: function(endpoint) {
    return new ws(endpoint,{headers: {"User-Agent": "nabaztag/0.1"}});
  },
  reconnectInterval: 5000,
};
const server = new simpleDDP(optsDDP);
```
