### ISSUE TITLE
server.on('event')

### ISSUE THREAD

**Issue by ddaydd** [Gregivy/simpleddp#32]
Hi, me again...

i found this for {msg: 'result'}
```javascript
server.on('result', (m) => {
  console.log(m);
});
//{ msg: 'result', id: '0' }
```

but is there a more global function for all events i could use this way?
```javascript
server.on('event', (e) => {
  console.log(e);
  if(e.msg === 'command'){
     console.log(e.job)
  }
});
//{ msg: 'command', job: 'turnOnLight' }
```

excuse me if it's not the right way to do it

_otherwise I can communicate with "result" but it's dirty ..._

thanks :)

**Comment by Gregivy** [comment]
Hi!

`server.on()` uses `EventEmitter` under the hood https://github.com/Olical/EventEmitter/blob/master/docs/guide.md. And yes you can use regular expressions instead of string event name, to capture all the events use:
```js
server.on(/.*/, (e) => {
  // do something here
});
```

**Comment by ddaydd** [comment]
Thanks :)
