### ISSUE TITLE
Meteor.loggingIn() equivalent 

### ISSUE THREAD

**Issue by odesey** [Gregivy/simpleddp#40]
I am testing your package as a replacement for `react-native-meteor` and was wondering is there is a replacement for the `Meteor.loggingIn()` method? I used this check in combination with `Meteor.user()` to know if the user was logged in or not.

```javascript
if( !Meteor.loggingIn() ) {
   if (Meteor.user()) {
    //user is logged in
  } else {
   //user is a guest and not logged in
  }
}

```
How can I get the same pattern with your package?

Thanks.

**Comment by DeanKamali** [comment]
According to [docs](https://github.com/Gregivy/simpleddp-plugin-login), `simpleDDP.login(auth)` the function returns a Promise which resolves to the object with userId of the logged-in user when the login succeeds or rejects when it fails.

Here is an [example](https://github.com/Gregivy/simpleddp-plugin-login): 

```
server.userId; // undefined, we are not logged in

let password = "somepassword";
let username = "admin";
let email = "admin@admin";

// you must pass password and at least one of username or email
let userAuth = await server.login({
  password,
  user: {
      username,
      email
  }
});

server.userId; // now equals to 'd6PqCAKk2QZeqZHWy'
server.token; // now equals to 'N50Gmknk__geP63YD9pHKdl07b8XXxNGpB_cz5Lte4d'
```

Hope this helps

**Comment by odesey** [comment]
Thanks for the quick response @DeanKamali 

So I guess I will have to implement my own `Meteor.user()` subscription or method in order to get the user's data once they are logged in?

Thanks.

**Comment by DeanKamali** [comment]
@odesey 

`Meteor.user()` will retrieve logged in user document from meteor's user collection, I guess what you are looking for is creating a reactive object after user is logged in: 

based on the previous example, after successful auth, you will have access to `server.userId`, you can then create a reactive object like so:
```
if (server.userId) {
let userReactiveCursor = server.collection('users').filter(user=>user.id==userId).reactive().one();
let userReactiveObject = userReactiveCursor.data(); // userReactiveObject is equivalent to `Meteor.user()`
}
```

**Comment by odesey** [comment]
Thanks for your help @DeanKamali , I was able to get this working in my `react-native` app.
