### ISSUE TITLE
Struggling to get data from ddp endpoint

### ISSUE THREAD

**Issue by ryanalbrecht** [Gregivy/simpleddp#43]
Hi There,

I am struggling to get data from a ddp enpoint. I have had success with other ddp clients but I would like to use this one as it seems to be more active.

Given the following code.
```
const simpleDDP = require("simpleddp"); // nodejs
const ws = require("isomorphic-ws");

let opts = {
  endpoint: "wss://livetiming.alkamelsystems.com/websocket",
  SocketConstructor: ws,
};

const server = new simpleDDP(opts);

(async ()=>{
  let livetimingSub = server.subscribe("livetimingFeed", "imsa");
  await livetimingSub.ready();
  let data = server.collection('feeds').fetch()
  console.log(data)
})()
```
The resultant `data` variable is an empty array, I can however see that the `feeds` collection is returning data, I just cannot seem to access using the package.

![image](https://user-images.githubusercontent.com/21182836/88696100-6e40d280-d0c8-11ea-8f78-f1d5b6468317.png)

Kind Regards
Ryan

**Comment by ryanalbrecht** [comment]
Nevermind.

**Comment by hcurnor** [comment]
@ryanalbrecht  how did you resolve your issue?
