### ISSUE TITLE
Redux-Saga

### ISSUE THREAD

**Issue by hanimay** [Gregivy/simpleddp#5]
What's the best way to integrate subscriptions and methods with Redux-Saga ?

**Comment by Gregivy** [comment]
I have not worked with Redux-Saga, but I suspect that you should use https://github.com/Gregivy/simpleddp/blob/2.x.x/api.md#ddpReactiveCollection+onChange or https://github.com/Gregivy/simpleddp/blob/2.x.x/api.md#ddpReactiveDocument+onChange or https://github.com/Gregivy/simpleddp/blob/2.x.x/api.md#ddpReducer+onChange for subscriptions. As for methods you can deal with them as with any other async request (like ajax).

**Comment by Gregivy** [comment]
I am closing it for now. If you have any questions feel free to reopen.
