### ISSUE TITLE
Use it in Meteor create --bare

### ISSUE THREAD

**Issue by ralphievolt** [Gregivy/simpleddp#6]
I just recently read about Meteor create --bare which removes minomongo from Meteor client.
Now I really want to use **simpleddp** and have it results save on my hook state management library so that I will not depend anymore on minimongo...

Hope you can show me a very simple example or show me to a right directions.

Thanks and great job on simpleddp.

**Comment by Gregivy** [comment]
Thank you @ralphievolt!

First of all you should take care about ES6 polyfills if you aim old browsers.

You can control yourself where you need the reactivity, the easiest way is do something like this in client code:
```
// client.js

import { Meteor } from 'meteor/meteor';
import simpleDDP from 'simpleDDP'; // ES6
import ws from 'isomorphic-ws';

let opts = {
    endpoint: "ws://" + window.location.hostname + "/websocket",
    SocketConstructor: ws,
    autoConnect: false,
    reconnectInterval: 5000
};
export const server = new simpleDDP(opts);

Meteor.startup(function(){
   server.connect();
});
```
Now you can import `server` variable anywhere you need to perform a subscription or call a method.

Everything else depends on what frontend framework you are using (React, Angular, etc). 

The important thing is that you have to control the unsubscribing process yourself, so when you don't need the subscription (for example user leaves some page) you should destroy it with https://github.com/Gregivy/simpleddp/blob/2.x.x/api.md#ddpSubscription+remove . The same concerns `ddpReactiveCollection`, `ddpReactiveDocument`, `ddpReducer` classes.
